# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [3]:
import pandas as pd

In [4]:
df1 = pd.read_csv('file1.csv')
df2 = pd.read_csv('file2.csv')
df3 = pd.read_csv('file3.csv')

In [5]:
df1.columns = df1.columns.str.lower()
df1.columns = df1.columns.str.replace(" ", "_")
df1.rename(columns={"st": "state"}, inplace=True)
df1.head(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834

In [6]:
df1["gender"] = df1["gender"].replace({
    "Male": "M",
    "female": "F",
    "Femal": "F"
})
df1["gender"].unique()

<StringArray>
[nan, 'F', 'M']
Length: 3, dtype: str

In [7]:
df1["state"] = df1["state"].replace({
    "Arizona": "AZ",
    "Nevada": "NV",
    "California": "CA",
    "Cali": "CA",
    "Oregon": "OR",
    "Washington": "WA"
})
df1["state"].unique()

<StringArray>
['WA', 'AZ', 'NV', 'CA', 'OR', nan]
Length: 6, dtype: str

In [8]:
df1["education"] = df1["education"].replace({
    "Bachelors": "Bachelor"
})
df1["education"].unique()

<StringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str

In [9]:
df1["customer_lifetime_value"] = df1["customer_lifetime_value"].str.replace("%", "")
df1["customer_lifetime_value"].unique()

<StringArray>
[         nan,  '697953.59', '1288743.17',  '764586.18',  '536307.65',
  '825629.78',  '538089.86',  '721610.03', '2412750.40',  '738817.81',
 ...
  '943891.56', '1050677.17',  '421391.86',  '477368.64',  '544142.01',
  '284226.69',  '305955.03', '2031499.76',  '323912.47',  '899704.02']
Length: 1028, dtype: str

In [10]:
df1["vehicle_class"] = df1["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})
df1["vehicle_class"].unique()

<StringArray>
['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan]
Length: 5, dtype: str

In [11]:
df1["number_of_open_complaints"] = df1["number_of_open_complaints"].str.split("/").str[1]

In [12]:
df1["number_of_open_complaints"].unique()

array(['0', '2', '1', '3', '5', '4', nan], dtype=object)

In [13]:
df1["customer_lifetime_value"] = df1["customer_lifetime_value"].astype("float64")

In [14]:
df1["monthly_premium_auto"] = df1["monthly_premium_auto"].astype("float64")

In [15]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     954 non-null    str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(4), object(1), str(6)
memory usage: 344.6+ KB

In [16]:
df1.head(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,WA,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,AZ,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,NV,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,CA,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,WA,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
5,OC83172,OR,F,Bachelor,825629.78,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042
6,XZ87318,OR,F,College,538089.86,55350.0,67.0,0,Corporate Auto,Four-Door Car,321.600000
7,CF85061,AZ,M,Master,721610.03,0.0,101.0,0,Corporate Auto,Four-Door Car,363.029680
8,DY87989,OR,M,Bachelor,2412750.40,14072.0,71.0,0,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,OR,F,College,738817.81,28812.0,93.0,0,Special Auto,Four-Door Car,425.527834

In [17]:
df2.columns = df2.columns.str.lower()
df2.columns = df2.columns.str.replace(" ", "_")
df2.rename(columns={"st": "state"}, inplace=True)
df2.head(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.200000,Corporate Auto,Two-Door Car
5,WL99637,Arizona,M,Bachelor,761413.80%,27293,96,1/0/00,469.030907,Personal Auto,Two-Door Car
6,UC84059,California,F,Master,689845.53%,70950,171,1/0/00,565.929394,Personal Auto,Sports Car
7,HW62747,Oregon,M,College,229837.92%,0,63,1/0/00,302.400000,Corporate Auto,Four-Door Car
8,BH11344,Oregon,F,Doctor,280669.61%,37009,71,1/0/00,145.673348,Corporate Auto,Two-Door Car
9,TX28465,Nevada,M,College,520611.82%,52629,65,1/0/00,136.684141,Personal Auto,Four-Door Car

In [18]:
df2["gender"] = df2["gender"].replace({
    "Male": "M",
    "female": "F",
    "Femal": "F"
})
df2["gender"].unique()

<StringArray>
['F', 'M', nan]
Length: 3, dtype: str

In [19]:
df2["state"] = df2["state"].replace({
    "Arizona": "AZ",
    "Nevada": "NV",
    "California": "CA",
    "Cali": "CA",
    "Oregon": "OR",
    "Washington": "WA"
})
df2["state"].unique()

<StringArray>
['AZ', 'CA', 'OR', 'NV', 'WA']
Length: 5, dtype: str

In [20]:
df2["education"] = df2["education"].replace({
    "Bachelors": "Bachelor"
})
df2["education"].unique()

<StringArray>
['Bachelor', 'Master', 'College', 'Doctor', 'High School or Below']
Length: 5, dtype: str

In [21]:
df2["customer_lifetime_value"] = df2["customer_lifetime_value"].str.replace("%", "")
df2["customer_lifetime_value"].unique()

<StringArray>
[ '323912.47',  '462680.11',  '899704.02', '2580706.30',  '380812.21',
  '761413.80',  '689845.53',  '229837.92',  '280669.61',  '520611.82',
 ...
  '446299.70', '1315183.20', '1401997.55',  '293115.52',  '477475.17',
  '847141.75',  '543121.91',  '568964.41',  '368672.38',  '399258.39']
Length: 951, dtype: str

In [22]:
df2["vehicle_class"] = df2["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})
df2["vehicle_class"].unique()

<StringArray>
['Four-Door Car', 'SUV', 'Two-Door Car', 'Luxury']
Length: 4, dtype: str

In [23]:
df2["number_of_open_complaints"] = df2["number_of_open_complaints"].str.split("/").str[1]
df2["number_of_open_complaints"].unique()

array(['0', '1', '3', '5', '2', '4'], dtype=object)

In [24]:
df2["customer_lifetime_value"] = df2["customer_lifetime_value"].astype("float64")

In [25]:
df2["number_of_open_complaints"] = df2["number_of_open_complaints"].astype("int64")

In [26]:
df2["income"] = df2["income"].astype("float64")

In [27]:
df2["monthly_premium_auto"] = df2["monthly_premium_auto"].astype("float64")

In [28]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   996 non-null    str
 1   state                      996 non-null    str
 2   gender                     991 non-null    str
 3   education                  996 non-null    str
 4   customer_lifetime_value    992 non-null    float64
 5   income                     996 non-null    float64
 6   monthly_premium_auto       996 non-null    float64
 7   number_of_open_complaints  996 non-null    int64
 8   total_claim_amount         996 non-null    float64
 9   policy_type                996 non-null    str
 10  vehicle_class              996 non-null    str
dtypes: float64(4), int64(1), str(6)
memory usage: 85.7 KB

In [29]:
df2.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,AZ,F,Bachelor,323912.47,16061.0,88.0,0,633.6,Personal Auto,Four-Door Car
1,CW49887,CA,F,Master,462680.11,79487.0,114.0,0,547.2,Special Auto,SUV
2,MY31220,CA,F,College,899704.02,54230.0,112.0,0,537.6,Personal Auto,Two-Door Car
3,UH35128,OR,F,College,2580706.30,71210.0,214.0,1,1027.2,Personal Auto,Luxury
4,WH52799,AZ,F,College,380812.21,94903.0,94.0,0,451.2,Corporate Auto,Two-Door Car

In [30]:
df3.columns = df3.columns.str.lower()
df3.columns = df3.columns.str.replace(" ", "_")
df3.rename(columns={"st": "state"}, inplace=True)
df3.head(10)

,customer,state,customer_lifetime_value,education,gender,income,monthly_premium_auto,number_of_open_complaints,policy_type,total_claim_amount,vehicle_class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV
5,VI78454,Arizona,2750.705045,College,M,51789,70,0,Personal Auto,336.000000,Four-Door Car
6,FP59138,Oregon,13024.130120,Master,M,0,125,0,Personal Auto,900.000000,SUV
7,XN62489,Oregon,2538.626320,Bachelor,M,18608,71,0,Corporate Auto,340.800000,Four-Door Car
8,GP66031,California,2585.955652,College,F,83758,64,0,Corporate Auto,106.591949,Two-Door Car
9,IX68587,Nevada,5096.673223,Master,F,22886,65,0,Personal Auto,312.000000,Four-Door Car

In [31]:
df3["gender"] = df3["gender"].replace({
    "Male": "M",
    "female": "F",
    "Femal": "F"
})
df3["gender"].unique()

<StringArray>
['M', 'F']
Length: 2, dtype: str

In [32]:
df3["state"] = df3["state"].replace({
    "Arizona": "AZ",
    "Nevada": "NV",
    "California": "CA",
    "Cali": "CA",
    "Oregon": "OR",
    "Washington": "WA"
})
df3["state"].unique()

<StringArray>
['WA', 'AZ', 'NV', 'CA', 'OR']
Length: 5, dtype: str

In [33]:
df3["education"] = df3["education"].replace({
    "Bachelors": "Bachelor"
})
df3["education"].unique()

<StringArray>
['High School or Below', 'Master', 'Bachelor', 'College', 'Doctor']
Length: 5, dtype: str

In [34]:
df3["vehicle_class"] = df3["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})
df3["vehicle_class"].unique()

<StringArray>
['Two-Door Car', 'Four-Door Car', 'SUV', 'Luxury']
Length: 4, dtype: str

In [35]:
df3["number_of_open_complaints"].unique()

array([0, 2, 3, 1, 5, 4])

In [36]:
df3["income"] = df3["income"].astype("float64")

In [37]:
df3["monthly_premium_auto"] = df3["monthly_premium_auto"].astype("float64")

In [38]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   7070 non-null   str
 1   state                      7070 non-null   str
 2   customer_lifetime_value    7070 non-null   float64
 3   education                  7070 non-null   str
 4   gender                     7070 non-null   str
 5   income                     7070 non-null   float64
 6   monthly_premium_auto       7070 non-null   float64
 7   number_of_open_complaints  7070 non-null   int64
 8   policy_type                7070 non-null   str
 9   total_claim_amount         7070 non-null   float64
 10  vehicle_class              7070 non-null   str
dtypes: float64(4), int64(1), str(6)
memory usage: 607.7 KB

In [39]:
df3.head(10)

,customer,state,customer_lifetime_value,education,gender,income,monthly_premium_auto,number_of_open_complaints,policy_type,total_claim_amount,vehicle_class
0,SA25987,WA,3479.137523,High School or Below,M,0.0,104.0,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,AZ,2502.637401,Master,M,0.0,66.0,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,NV,3265.156348,Bachelor,F,25820.0,82.0,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,CA,4455.843406,High School or Below,F,0.0,121.0,0,Personal Auto,699.615192,SUV
4,FN77294,CA,7704.958480,High School or Below,M,30366.0,101.0,2,Personal Auto,484.800000,SUV
5,VI78454,AZ,2750.705045,College,M,51789.0,70.0,0,Personal Auto,336.000000,Four-Door Car
6,FP59138,OR,13024.130120,Master,M,0.0,125.0,0,Personal Auto,900.000000,SUV
7,XN62489,OR,2538.626320,Bachelor,M,18608.0,71.0,0,Corporate Auto,340.800000,Four-Door Car
8,GP66031,CA,2585.955652,College,F,83758.0,64.0,0,Corporate Auto,106.591949,Two-Door Car
9,IX68587,NV,5096.673223,Master,F,22886.0,65.0,0,Personal Auto,312.000000,Four-Door Car

In [40]:
full_df = pd.concat([df1, df2, df3], axis=0, join='outer', keys=None)

In [41]:
full_df.info()

<class 'pandas.DataFrame'>
Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   str
 1   state                      9137 non-null   str
 2   gender                     9015 non-null   str
 3   education                  9137 non-null   str
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   str
 9   vehicle_class              9137 non-null   str
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(4), object(1), str(6)
memory usage: 1.1+ MB

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [42]:
marketing_df = pd.read_csv("marketing_customer_analysis_clean.csv")
marketing_df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [43]:
def total_revenue_by_channel(data):
    revenue_table = data.pivot_table(
        index="sales_channel",
        values="total_claim_amount",
        aggfunc="sum"
    )
    
    revenue_table = revenue_table.round(2)
    revenue_table = revenue_table.rename(columns={"total_claim_amount": "total_revenue"})
    revenue_table = revenue_table.sort_values("total_revenue", ascending=False)
    
    return revenue_table

In [44]:
sales_channel_revenue = total_revenue_by_channel(marketing_df)
sales_channel_revenue

               total_revenue
sales_channel
Agent             1810226.82
Branch            1301204.00
Call Center        926600.82
Web                706600.04

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [45]:
def average_clv_by_gender_and_education(data):
    clv_table = data.pivot_table(
        index="gender",
        columns="education",
        values="customer_lifetime_value",
        aggfunc="mean"
    )
    
    clv_table = clv_table.round(2)
    
    return clv_table

In [46]:
average_clv_table = average_clv_by_gender_and_education(marketing_df)
average_clv_table

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [47]:
def complaints_by_policy_type_and_month(data):
    complaints_table = data.pivot_table(
        index=["policy_type", "month"],
        values="number_of_open_complaints",
        aggfunc="sum"
    )
    
    complaints_table = complaints_table.round(0).astype(int)
    complaints_table = complaints_table.reset_index()
    
    return complaints_table

In [48]:
complaints_table = complaints_by_policy_type_and_month(marketing_df)
complaints_table

      policy_type  month  number_of_open_complaints
0  Corporate Auto      1                        443
1  Corporate Auto      2                        385
2   Personal Auto      1                       1728
3   Personal Auto      2                       1454
4    Special Auto      1                         87
5    Special Auto      2                         95